### ISSUE TITLE
Errors in 11.0 releases

### ISSUE THREAD

**Issue by TommyBigNose** [relativitydev/relativity-smoke-test-app#7]
Error Details:	SmokeTest.Exceptions.SmokeTestException: An error occured in Conversion Test. ErrorMessage: SmokeTest.Exceptions.SmokeTestException: An error occured during document conversion. ---> SmokeTest.Exceptions.SmokeTestException: An error occured getting the Max CacheId ---> SmokeTest.Exceptions.SmokeTestException: An error occured calling ExecuteSqlStatementAsScalar. ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToGenericParameter[T](Object Value)
   at SmokeTest.Helpers.ViewerHelper.GetMaxCacheId(Int32 documentId)
   --- End of inner exception stack trace ---
   at SmokeTest.Helpers.ViewerHelper.GetMaxCacheId(Int32 documentId)
   --- End of inner exception stack trace ---
   at SmokeTest.Helpers.ViewerHelper.GetMaxCacheId(Int32 documentId)
   at SmokeTest.Helpers.ViewerHelper.ConvertDocumentsForViewer(Int32 workspaceArtifactId)
   --- End of inner exception stack trace ---
   at SmokeTest.Helpers.ViewerHelper.ConvertDocumentsForViewer(Int32 workspaceArtifactId). Exception:
   at SmokeTest.SmokeTestCollection.RunTest(SmokeTestModel smokeTestModel, RDO testRdo)

**Comment by mrshanahan** [comment]
No longer maintaining this repository.
